# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: "**"
  push:
    branches: "**"

jobs:
  build:
    env:
      REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL_M }}
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
      REACT_APP_BLOG_S3_BASE_URL: https://wasedatime-feeds.s3-ap-northeast-1.amazonaws.com
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install
        run: |
          echo "Adding bit.dev to npm registry"
          npm config set --global @bit:registry https://node.bit.dev
          npm config set --global //node.bit.dev/:_authToken ${BIT_TOKEN}
          echo "Completed adding bit.dev to npm registry"
          cd root
          npm run ci-all
          
      - name: Test
        run: |
          cd root
          npm run test-all

      - name: build
        run: |
          cd root
          npm run build-all
